# -*- coding: utf-8 -*-
"""Copy of sdeflow_equivalent_sdes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tx_Yt90NRgHve--ocIXi6SGR-0ebwH0N
"""


import time
import numpy as np
import torch
import torch.nn as nn
import sys
import os
from transportNoise import mps_safe_gather, mps_safe_scatter_add_

def _field_norm(x):
    """
    L2 "energy" norm of the field per batch element, used by norm_correction.
    For FFTfields (x: (B,n,2) real/imag flat vector), this is the norm of
    the complex modulus per mode, sqrt(real^2+imag^2), combining both
    channels -- mathematically identical to flattening both channels
    together and taking a single L2 norm (sum|z_k|^2 = sum(re_k^2+im_k^2)),
    but written explicitly so the combination across channels is
    unambiguous rather than relying on that identity implicitly.
    """
    if x.dim() == 3 and x.shape[-1] == 2:
        modulus = torch.sqrt(x[..., 0] ** 2 + x[..., 1] ** 2)   # (B,n)
        return torch.norm(modulus, dim=1)
    return torch.norm(x.reshape(x.shape[0], -1), dim=1)

def _mps_cache_clear(device):
    """Frees unused MPS memory; without this, long step loops slowly OOM. No-op elsewhere."""
    if isinstance(device, torch.device) and device.type == 'mps':
        torch.mps.empty_cache()

def _sample_dW(x_t, delta, two_noise):
    """
    One real scalar Wiener increment per mode (not per channel). For AMSGM,
    the noise is 2-dimensional per mode (dB^R_t(k), dB^I_t(k) -- see
    transportNoise.grid_k.build_sparse_G), so two independent draws are
    returned as a tuple, matching sigma's own (sigma_R, sigma_I) tuple from
    MSGMsde.g/PluginReverseSDE.sigma (see EMstep).
    """
    if two_noise:
        return (delta ** 0.5 * torch.randn(x_t.shape[:2], device=x_t.device),
                delta ** 0.5 * torch.randn(x_t.shape[:2], device=x_t.device))
    return delta ** 0.5 * torch.randn(x_t.shape[:2], device=x_t.device)

@torch.no_grad()
def EMstep(mu, delta, sigma, dW, sparse=False, I=None, K=None):
    """
    sigma, dW: either a single tensor each (one-noise case), or a
    (sigma_R, sigma_I)/(dW_R, dW_I) pair -- the two independent real noises
    dB^R_t(k), dB^I_t(k) driving A-MSGM's 2-dimensional-per-mode advection
    tensor (G^R skew/per-channel, G^I symmetric/cross-channel; see
    transportNoise.py). Each pair's diffusion contribution is computed
    identically to the one-noise case and the two are summed.

    sigma:
       dense case  -> (B,n,n)
       sparse case -> (B,nnz) or (B,nnz,2) with a trailing real/imag channel
                       (FFTfields), same indexing as G_sparse.values()
    dW: (B,n), one real scalar Wiener increment per mode (not per channel)
    I,K: sparse indices
    """

    def _diffusion(sigma, dW):
        if sparse:
            # sigma[b,e] multiplies dW[b, K[e]], broadcasting the single
            # per-mode real dW across any trailing real/imag channel dim sigma
            # carries (FFTfields: (B,nnz,2)) -- see transportNoise.py for why a
            # single real dW per mode is correct here.
            dW_K = mps_safe_gather(dW, 1, K)              # (B, nnz)
            if sigma.dim() > dW_K.dim():
                dW_K = dW_K.unsqueeze(-1)
            prod = sigma * dW_K          # (B, nnz) or (B, nnz, 2)

            dx = torch.zeros_like(mu)    # (B,n) or (B,n,2) -- matches the state, not dW
            index = I.unsqueeze(0).expand(dW.size(0), -1)
            if prod.dim() > 2:
                index = index.unsqueeze(-1).expand(-1, -1, prod.shape[-1])
            mps_safe_scatter_add_(dx, 1, index, prod)
        else:
            # sigma is either a dense (B,n,n) diffusion matrix (needs a matvec via
            # einsum), or an elementwise/diagonal diffusion coefficient the same
            # shape as dW (just multiply) -- sigma.dim() alone can't distinguish
            # these once dW/sigma may carry a trailing real/imag channel dim
            # (FFTfields: (B,n,2)), since an elementwise sigma is then 3D too.
            if sigma.shape == dW.shape:
                dx = sigma * dW
            else:
                dx = torch.einsum('bij, bj -> bi', sigma, dW)
        return dx

    if isinstance(sigma, tuple):
        dx = sum(_diffusion(s, w) for s, w in zip(sigma, dW))
    else:
        dx = _diffusion(sigma, dW)

    return mu * delta + dx

### 2.0 Define Euler Maruyama method with a step size $\Delta t$
@torch.no_grad()
def euler_maruyama_sampler(sde, x_0, num_steps=1000, lmbd=0., 
                             keep_all_samples=True, samplesToKeep=None,
                             include_t0=False, T_=-1, norm_correction = False):
    """
    Euler Maruyama method with a step size delta
    """
    # init
    device = sde.T.device
    batch_size = x_0.size(0)
    ndim = x_0.dim()-1
    if T_ == -1 :
        T_ = sde.T.item()
    else:
        T_ = T_.item()
    delta = T_ / num_steps
    ts = torch.linspace(0, 1, num_steps + 1) * T_
    sparseG = sde.base_sde.sparseTensor
    I, J, K = sde.base_sde.IJK()
    two_noise = sparseG and sde.base_sde.AMSGM

    # sample
    x_t = x_0.detach().clone().to(device)
    if norm_correction:
        norm_x_0 = _field_norm(x_t)
    if keep_all_samples :
        if (not include_t0) :
            xs = torch.zeros((*x_0.shape,num_steps),device='cpu',dtype=x_0.dtype)
        else :
            xs = torch.zeros((*x_0.shape,num_steps+1),device='cpu',dtype=x_0.dtype)
            xs[...,0]=x_t.clone().to('cpu')
    elif samplesToKeep is not None:
        if not (len(samplesToKeep) == batch_size):
            raise ValueError('Error: len(samplesToKeep) must correspond to batch size.')
        xs = torch.zeros_like(x_0, device='cpu')

    t = torch.zeros(batch_size, *([1]*ndim), device=device)
    with torch.no_grad():
        for i in range(num_steps):
            t.fill_(ts[i].item())
            mu = sde.mu(t, x_t, lmbd=lmbd)
            sigma = sde.sigma(t, x_t, lmbd=lmbd, sparse=sparseG)
            dW = _sample_dW(x_t, delta, two_noise)
            x_t = x_t + EMstep(mu, delta , sigma , dW, sparse=sparseG, I=I, K=K)
            if norm_correction:
                ratio = (norm_x_0 / _field_norm(x_t))
                x_t = x_t * ratio.reshape(x_t.shape[0], *([1] * (x_t.dim() - 1)))
            if keep_all_samples:
                xs[...,i+include_t0]=x_t.clone().to('cpu')
            elif samplesToKeep is not None:
                if (i+include_t0) in samplesToKeep:
                    idx_samplesToKeep = (samplesToKeep == (i+include_t0)).flatten()
                    xs[idx_samplesToKeep,:]=x_t[idx_samplesToKeep,:].clone().to('cpu')
            _mps_cache_clear(device)

    if keep_all_samples:
        xs = torch.permute(xs, (xs.dim() - 1,) + tuple(range(xs.dim() - 1)))  # move time axis (last) to front
    elif samplesToKeep is None:
        xs=x_t.clone().to('cpu')

    return xs.to('cpu')

@torch.no_grad()
def heun_sampler(sde, x_0, num_steps=1000, lmbd=0.,
                             keep_all_samples=True, samplesToKeep=None,
                             include_t0=False, T_=-1, norm_correction = False):
    """
    Heun method (Runge-Kutta 2) for SDEs in Stratonovich form.
    """
    # Initialization
    device = sde.T.device
    batch_size = x_0.size(0)
    ndim = x_0.dim() - 1
    if T_ == -1 :
        T_ = sde.T.item()
    else:
        T_ = T_.item()
    delta = T_ / num_steps
    ts = torch.linspace(0, 1, num_steps + 1) * T_
    sparseG = sde.base_sde.sparseTensor
    I, J, K = sde.base_sde.IJK()
    two_noise = sparseG and sde.base_sde.AMSGM

    # Sampling
    x_t = x_0.detach().clone().to(device)
    if norm_correction:
        norm_x_0 = _field_norm(x_t)
    t = torch.zeros(batch_size, *([1] * ndim), device=device)
    if keep_all_samples :
        if (not include_t0) :
            xs = torch.zeros((*x_0.shape,num_steps),device='cpu',dtype=x_0.dtype)
        else :
            xs = torch.zeros((*x_0.shape,num_steps+1),device='cpu',dtype=x_0.dtype)
            xs[...,0]=x_t.clone().to('cpu')
    elif samplesToKeep is not None:
        if not (len(samplesToKeep) == batch_size):
            raise ValueError('Error: len(samplesToKeep) must correspond to batch size.')
        xs = torch.zeros_like(x_0, device='cpu')
        
    with torch.no_grad():
        for i in range(num_steps):
            t.fill_(ts[i].item())

            # Compute mu and sigma at the start of the interval
            mu_1 = sde.mu_Strato(t, x_t, lmbd=lmbd)
            sigma_1 = sde.sigma(t, x_t, lmbd=lmbd, sparse=sparseG)
            dW = _sample_dW(x_t, delta, two_noise)

            # Predictor step (Euler)
            x_predict = x_t + EMstep(mu_1, delta , sigma_1 , dW, sparse=sparseG, I=I, K=K)
            # x_predict = x_t + delta * mu_1 + sigma_1 * dW

            # Corrector step
            mu_2 = sde.mu_Strato(t + delta, x_predict, lmbd=lmbd)
            sigma_2 = sde.sigma(t + delta, x_predict, lmbd=lmbd, sparse=sparseG)

            # Average drift and diffusion terms
            # x_t = x_t + (delta / 2) * (mu_1 + mu_2) + (sigma_1 + sigma_2) * (dW / 2)
            if two_noise:
                sigma_sum = tuple(s1 + s2 for s1, s2 in zip(sigma_1, sigma_2))
                dW_half = tuple(w / 2 for w in dW)
            else:
                sigma_sum = sigma_1 + sigma_2
                dW_half = dW / 2
            x_t = x_t + EMstep(mu_1 + mu_2, delta / 2 , sigma_sum , dW_half, sparse=sparseG, I=I, K=K)
            if norm_correction:
                ratio = (norm_x_0 / _field_norm(x_t))
                x_t = x_t * ratio.reshape(x_t.shape[0], *([1] * (x_t.dim() - 1)))

            if keep_all_samples:
                xs[...,i+include_t0]=x_t.clone().to('cpu')
            elif samplesToKeep is not None:
                if (i+include_t0) in samplesToKeep:
                    idx_samplesToKeep = (samplesToKeep == (i+include_t0)).flatten()
                    xs[idx_samplesToKeep,:]=x_t[idx_samplesToKeep,:].clone().to('cpu')
            _mps_cache_clear(device)

    if keep_all_samples:
        xs = torch.permute(xs, (xs.dim() - 1,) + tuple(range(xs.dim() - 1)))  # move time axis (last) to front
    elif samplesToKeep is None:
        xs=x_t.clone().to('cpu')

    return xs.to('cpu')

@torch.no_grad()
def rk4_stratonovich_sampler(sde, x_0, num_steps=1000, lmbd=0.,
                             keep_all_samples=True, samplesToKeep=None,
                             include_t0=False, T_=-1, norm_correction = False):
    """
    Runge-Kutta 4th order method for Stratonovich SDEs with skew-symmetric noise.
    
    Args:
        sde: an object with methods `mu(t, x, lmbd)` and `sigma(t, x, lmbd)`
            representing the drift and diffusion terms of the SDE.
        x_0: initial condition, torch tensor of shape (batch_size, ...)
        num_steps: number of time steps for the integration.
        lmbd: additional parameter passed to `mu` and `sigma`.
        keep_all_samples: whether to store all intermediate samples.
    
    Returns:
        List of samples if keep_all_samples is True, otherwise only the final state.
    """
    # Initialization
    device = sde.T.device
    batch_size = x_0.size(0)
    ndim = x_0.dim() - 1
    if T_ == -1 :
        T_ = sde.T.item()
    else:
        T_ = T_.item()
    delta = T_ / num_steps
    ts = torch.linspace(0, 1, num_steps + 1) * T_

    x_t = x_0.detach().clone().to(device)
    if norm_correction:
        norm_x_0 = _field_norm(x_t)
    t = torch.zeros(batch_size, *([1] * ndim), device=device)
    if keep_all_samples :
        if (not include_t0) :
            xs = torch.zeros((*x_0.shape,num_steps),device='cpu',dtype=x_0.dtype)
        else :
            xs = torch.zeros((*x_0.shape,num_steps+1),device='cpu',dtype=x_0.dtype)
            xs[...,0]=x_t.clone().to('cpu')
    elif samplesToKeep is not None:
        if not (len(samplesToKeep) == batch_size):
            raise ValueError('Error: len(samplesToKeep) must correspond to batch size.')
        xs = torch.zeros_like(x_0, device='cpu')
    
    sparseG = sde.base_sde.sparseTensor
    I, J, K = sde.base_sde.IJK()
    two_noise = sparseG and sde.base_sde.AMSGM

    with torch.no_grad():
        for i in range(num_steps):
            t.fill_(ts[i].item())

            dW = _sample_dW(x_t, delta, two_noise)  # one real scalar per mode per noise channel, see EMstep
            
            # Stage 1
            mu_Strato_1 = sde.mu_Strato(t, x_t, lmbd=lmbd)
            sigma_1 = sde.sigma(t, x_t, lmbd=lmbd, sparse=sparseG)
            K1 = EMstep(mu_Strato_1, delta, sigma_1, dW, sparse=sparseG, I=I, K=K)
            
            # Stage 2
            x_mid = x_t + K1 / 2
            mu_Strato_2 = sde.mu_Strato(t + delta / 2, x_mid, lmbd=lmbd)
            sigma_2 = sde.sigma(t + delta / 2, x_mid, lmbd=lmbd, sparse=sparseG)
            K2 = EMstep(mu_Strato_2 , delta, sigma_2 , dW, sparse=sparseG, I=I, K=K)
            
            # Stage 3
            x_mid = x_t + K2 / 2
            mu_Strato_3 = sde.mu_Strato(t + delta / 2, x_mid, lmbd=lmbd)
            sigma_3 = sde.sigma(t + delta / 2, x_mid, lmbd=lmbd , sparse=sparseG)
            K3 = EMstep(mu_Strato_3 ,delta,  sigma_3 , dW, sparse=sparseG, I=I, K=K)
            
            # Stage 4
            x_end = x_t + K3
            mu_Strato_4 = sde.mu_Strato(t + delta, x_end, lmbd=lmbd)
            sigma_4 = sde.sigma(t + delta, x_end, lmbd=lmbd , sparse=sparseG)
            K4 = EMstep(mu_Strato_4, delta , sigma_4 , dW, sparse=sparseG, I=I, K=K)
            
            # Combine stages (weighted sum)
            x_t = x_t + (K1 + 2 * K2 + 2 * K3 + K4) / 6
            if norm_correction:
                ratio = (norm_x_0 / _field_norm(x_t))
                x_t = x_t * ratio.reshape(x_t.shape[0], *([1] * (x_t.dim() - 1)))

            if keep_all_samples:
                xs[...,i+include_t0]=x_t.clone().to('cpu')
            elif samplesToKeep is not None:
                if (i+include_t0) in samplesToKeep:
                    idx_samplesToKeep = (samplesToKeep == (i+include_t0)).flatten()
                    xs[idx_samplesToKeep,:]=x_t[idx_samplesToKeep,:].clone().to('cpu')
            _mps_cache_clear(device)

    if keep_all_samples:
        xs = torch.permute(xs, (xs.dim() - 1,) + tuple(range(xs.dim() - 1)))  # move time axis (last) to front
    elif samplesToKeep is None:
        xs=x_t.clone().to('cpu')
    
    return xs.to('cpu')
