# -*- coding: utf-8 -*-
"""modification of sdeflow_equivalent_sdes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tx_Yt90NRgHve--ocIXi6SGR-0ebwH0N
    associated to https://github.com/CW-Huang/sdeflow-light
"""


import time
import numpy as np
import torch
import torch.nn as nn
import copy
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats.mstats import mquantiles
from sklearn.neighbors import KernelDensity
from scipy.stats import norm
import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from sde_scheme import euler_maruyama_sampler,heun_sampler,rk4_stratonovich_sampler,EMstep
import gc
from transportNoise import fourier_flat_to_spatial, spatial_flat_to_fourier, \
                           mps_safe_gather, mps_safe_scatter_add_, \
                           sparse_yJ_products, meanflow_beta_vectors, build_advection_state


# class OU_SDE(torch.nn.Module): 
class forward_SDE(torch.nn.Module): 

    def __init__(self, base_sde, T):
        super().__init__()
        self.base_sde = base_sde
        self.T = T
    
    # Ito drift
    def mu(self, s, y, lmbd=0.):
        return self.mu_Strato(s, y) + 0.5 * self.base_sde.div_Sigma(s, y)
    
    # Stratonovich Drift
    def mu_Strato(self, s, y, lmbd=0.):
        return self.base_sde.f_strato(s, y) 
    
    # Diffusion
    def sigma(self, s, y, lmbd=0., sparse = False):
        return self.base_sde.g(s, y, sparse = sparse)

class SDE(torch.nn.Module):
    """
    parent class for SDE
    """
    # This class need to be changed since the forward SDE cannot be solved analitically
    def __init__(self, beta_min=0.1, beta_max=20.0, T=1.0, t_epsilon=0.001, num_steps_forward = 100, device="cpu"):
        super().__init__()
        self.device = torch.device(device)
        self.T = T
        self.beta_min = beta_min
        self.beta_max = beta_max
        self.t_epsilon = t_epsilon
        # self.forward_SDE = forward_SDE(self, self.T).to(device)
        self.num_steps_forward = num_steps_forward
        self.norm_correction = False
        self.sparseTensor = False
        self.FFTfields = False
        self.AMSGM = False

    def to(self, device):
        new = super().to(device)
        new.device = torch.device(device)
        new.T = self.T.to(device)
        return new

    def beta(self, t):
        return self.beta_min + (self.beta_max-self.beta_min)*t

    def IJK(self):
        return None, None, None

    @torch.no_grad()
    def sample_scheme(self, t, y0, keep_all_samples, return_noise=False):
        """
        sample yt | y0
        """
        if return_noise:
            raise NotImplementedError('See the official repository.')

        num_steps_tot = self.num_steps_forward
        include_t0=True

        num_steps_floats = num_steps_tot * t/self.T
        num_steps_int = torch.trunc(num_steps_floats).to(torch.int).to('cpu')

        # WARNING : this sampler is used (many times) for t=T 
        # another method should be used here instead
        if any(t >= self.T):
            print('warning : t >= T')
            for k in range(y0.shape[0]):
                if t[k] >= self.T: 
                    if include_t0:
                        num_steps_int[k] = num_steps_tot
                    else:
                        num_steps_int[k] = num_steps_tot - 1

        yt = torch.zeros_like(y0)
        y_allt = self.sample_scheme_allt(y0, include_t0=include_t0, 
                                        keep_all_samples=keep_all_samples, samplesToKeep=num_steps_int)
        for k in range(y0.shape[0]):
            if num_steps_int[k]>0 :
                if keep_all_samples:
                    yt[k,:] = y_allt[num_steps_int[k],k,:]
                else:
                    yt[k,:] = y_allt[k,:]
            else:
                # print('warning : small random time')
                ytemp = rk4_stratonovich_sampler(forward_SDE(self, self.T).to(self.device), 
                                                    y0[k,:][np.newaxis, ...], 1, 
                                                    lmbd=0, keep_all_samples=False, include_t0=False, T_ = t[k])
                yt[k,:] = ytemp[0,:]
                del ytemp
        
        del y_allt, num_steps_int

        return yt.to(self.device)

    @torch.no_grad()
    def sample_scheme_allt(self, y0, include_t0=True, keep_all_samples=True, samplesToKeep=None):
        """
        sample y0, y_t_1, y_t_2, ..., y_T | y0
        """

        return rk4_stratonovich_sampler(forward_SDE(self, self.T).to(self.device), y0, num_steps=self.num_steps_forward, \
                                          lmbd=0, keep_all_samples=keep_all_samples, samplesToKeep=samplesToKeep, 
                                          include_t0=include_t0) # sample

    def sample_Song_et_al(self, t, y0, return_noise=False):
        """
        sample yt | y0
        if return_noise=True, also return std and g for reweighting the denoising score matching loss
        """
        mu = self.mean_weight(t) * y0
        std = self.var(t) ** 0.5
        epsilon = torch.randn_like(y0)
        yt = epsilon * std + mu
        if not return_noise:
            return yt
        else:
            return yt, epsilon, std, self.g(t, yt)

    def sample_debiasing_t(self, shape):
        """
        non-uniform sampling of t to debias the weight std^2/g^2
        the sampling distribution is proportional to g^2/std^2 for t >= t_epsilon
        for t < t_epsilon, it's truncated
        """
        raise NotImplementedError('See the official repository.')
        # return sample_vp_truncated_q(shape, self.beta_min, self.beta_max, t_epsilon=self.t_epsilon, T=self.T)


Log2PI = float(np.log(2 * np.pi))


class SGMsde(SDE):
    """
    Implementation of the variance preserving SDE proposed by Song et al. 2021
    See eq (32-33) of https://openreview.net/pdf?id=PxTIG12RRHS
    """
    # This class need to be changed since the forward SDE cannot be solved analitically
    def __init__(self, beta_min=0.1, beta_max=20.0, T=1.0, t_epsilon=0.001, num_steps_forward = 100, device='cpu'):
        super().__init__(beta_min=beta_min, beta_max=beta_max, T=T, t_epsilon=t_epsilon, num_steps_forward = num_steps_forward, device=device)
        self.name_SDE = "SGM"

    @property
    def logvar_mean_T(self):
        logvar = torch.zeros(1)
        mean = torch.zeros(1)
        return logvar, mean

    def mean_weight(self, t):
        return torch.exp(-0.25 * t**2 * (self.beta_max-self.beta_min) - 0.5 * t * self.beta_min)

    def var(self, t):
        return 1. - torch.exp(-0.5 * t**2 * (self.beta_max-self.beta_min) - t * self.beta_min)

    def f(self, t, y):
        return - 0.5 * self.beta(t) * y

    def f_strato(self, t, y):
        return - 0.5 * self.beta(t) * y

    def div_Sigma(self, t, y):
        return torch.zeros_like(y)

    def g(self, t, y, sparse = False):
        beta_t = self.beta(t)
        return torch.ones_like(y) * beta_t**0.5

    @torch.no_grad()
    def sample(self, t, y0, return_noise=False):
        # return self.sample_scheme(t, y0)
        return self.sample_Song_et_al(t, y0, return_noise)

    def latent_sample(self,num_samples, n):
        # init from prior
        return torch.randn(num_samples, n, device=self.device) 
    
    def cond_latent_sample(self,t_, T, x):
        # conditionnal latent sample of yT knowing x=y0
        return self.sample(torch.ones_like(t_) * T, x)
    
    def log_latent_pdf(self,yT):
        # log of latent pdf
        return self.log_normal(yT, torch.zeros_like(yT), torch.zeros_like(yT))
    
    def log_normal(self,x, mean, log_var, eps=0.00001):
        z = - 0.5 * Log2PI
        return - (x - mean) ** 2 / (2. * torch.exp(log_var) + eps) - log_var / 2. + z
    

##########################################


class MSGMsde(SDE):
    """
    d Y = G(Y) o dB_t
    """
    # This class need to be changed since the forward SDE cannot be solved analitically
    def __init__(self, y0, beta_min=0.1, beta_max=20.0, T=1.0, t_epsilon=0.001, \
                 denseTensor = True, AMSGM = False, anti_aliasing = True, disable_noise = False, \
                 k_pattern = None, V0 = None, A_beta = None, \
                 norm_sampler = "ecdf", norm_map = None, kernel = 'gaussian', plot_validate = False, \
                 num_steps_forward = 100, device='cpu', estim_cst_norm_dens_r_T = True):
        super().__init__(beta_min=beta_min, beta_max=beta_max, T=T, t_epsilon=t_epsilon, 
                         num_steps_forward=num_steps_forward, device=device)
        self.sparseTensor = not denseTensor
        self.norm_correction = True
        self.r_T = torch.linalg.norm(y0.reshape(y0.shape[0], -1), dim= 1)
        self.norm_map = norm_map
        if norm_map == "log":
            self.r_T = torch.log(self.r_T + 1e-6)
        r_T = self.r_T.reshape(len(self.r_T),1)
        self.norm_sampler = norm_sampler
        bandwidth = 0.1*torch.std(r_T).item()
        self.kde = KernelDensity(kernel=kernel, bandwidth=bandwidth).fit(r_T.clone().detach().cpu())
        self.r_T = self.r_T.to(self.device)  # if you use it later in device ops
        self.dim = y0.shape[1]
        self.name_SDE = "MSGM"
        self.D_hyper = None
        self.AMSGM = AMSGM
        self.FFTfields = AMSGM
        self.anti_aliasing = anti_aliasing
        self.disable_noise = disable_noise
        # Deterministic mean-flow drift F Q(t): defaults to a moving
        # Taylor-Green streamfunction (transportNoise.grid_k.taylor_green_terms),
        # or pass k_pattern=[(k1,k2,unit_amplitude),...] to override. V0/A_beta
        # default to CFL-auto-sized (see sparse_G_advection); pass 0 to disable.
        self.k_pattern = k_pattern
        self.V0 = V0
        self.A_beta = A_beta
        if denseTensor:
            if AMSGM:
                raise NotImplemented("A-MSGM relies on sparse tensor")
            self.new_G(self.dim)
            self.L_G = 0.5*torch.einsum('ijk, jmk -> im', self.G, self.G)   # ito correction tensor
        else:
            if AMSGM:
                self.name_SDE += "_AMSGM"
                self.beta_min = 1
                self.beta_max = 1
                self.sparse_G_advection(self.dim)   # also sets self.L_G to the exact Ito correction
                if disable_noise:
                    # Zero the noise's effect (keeping the sparse structure
                    # intact) to visually check the pure Stratonovich drift alone.
                    self.G_V.zero_()
                    self.G_V_I.zero_()
                    self.L_G.zero_()
                    self.name_SDE += "_noNoise"
                if self.A_beta != 0:
                    self.name_SDE += "_drift"
            else:
                self.name_SDE += "_sparseTens"
                # self.sparse_G_full(self.dim) # FOR DEBUG ONLY
                self.sparse_G(self.dim)
                self.L_G = 0.5*torch.eye(self.dim, device=self.device)   # ito correction tensor
        if not (norm_sampler=="ecdf"):
            self.name_SDE += norm_sampler + kernel
        if norm_map == "log":
            self.name_SDE += "logNorm"
        if plot_validate:
            estim_cst_norm_dens_r_T = True
        if estim_cst_norm_dens_r_T:
            r_T = self.r_T.reshape(len(r_T),1)
            r_plot = torch.linspace(min(r_T[:,0]) ,max(r_T[:,0]), 1000).reshape(1000,1)
            log_dens = torch.tensor(self.kde.score_samples(r_plot)).to(torch.float32).to(device)
            dens = torch.exp(log_dens)
            dr = (r_plot[1,0]-r_plot[0,0])
            cst_dens = torch.sum(dens,dim=0)* dr
            self.cst_log_dens = torch.log(cst_dens)
        else:
            self.cst_log_dens = 0

        if plot_validate :   
            beta_G = - 2*torch.trace(self.L_G)/self.dim            
            if denseTensor:
                print("G")
                print(self.G[:,:,0])
                print(self.G[:,:,1])
            print("L_G")
            print(self.L_G)
            print("beta_G = " + str(beta_G))

            r_T_np_arr = r_T.clone().detach().cpu().numpy()
            res = stats.ecdf(r_T_np_arr.flatten())
            res.cdf.quantiles
            res.cdf.probabilities
            dens /= cst_dens
            print(cst_dens)
            cdf_dens_plot = torch.cumsum(dens,dim=0)* dr

            plt.plot(r_plot[:,0], dens, label='pdf kde')
            plt.plot(r_plot[:,0], cdf_dens_plot, label='cdf kde')
            plt.plot(res.cdf.quantiles, res.cdf.probabilities, label='ecdf')
            plt.legend()
            time.sleep(0.5)
            plt.show(block=False)
            name_fig = "ecdf_n_kde_" + kernel + \
                "_ensSize=" + str(len(r_T_np_arr.flatten())) + "_bw=" + str(bandwidth) + ".png"
            plt.savefig(name_fig)
            plt.pause(1)
            plt.close()
    
        if estim_cst_norm_dens_r_T:
            del log_dens, dens, r_plot 
        gc.collect()

    def to(self, device):
        new = super().to(device)
        new.r_T = self.r_T.to(device)
        if self.D_hyper is not None:
            new.D_hyper = self.D_hyper.to(device)
        if self.sparseTensor:
            new.G_I = self.G_I.to(device)
            new.G_J = self.G_J.to(device)
            new.G_K = self.G_K.to(device)
            new.G_V = self.G_V.to(device)
            if self.AMSGM:
                new.G_V_I = self.G_V_I.to(device)
        else:
            new.G = self.G.to(device)
        return new

    def new_G(self, n) : 
        # from n independent random matrices 
        G = torch.zeros(n,n,n,device=self.device) 
        for k in range(n): 
            F = torch.randn(n,n,device=self.device)
            F = 0.5 * (F - F.T)
            G[:,:,k] = F
        
        # normalisation to control how fast the dynamic is
        L_G = 0.5*torch.einsum('ijk, jmk -> im', G, G)   # ito correction tensor
        tr_L = torch.trace(L_G)
        G = torch.sqrt( - 0.5 * n / tr_L ) * G
        
        # check
        validate = False
        if validate:
            print(tr_L)
            for l in range(n): 
                print("G[:,l,:] of rank d-1 ?")
                print(G[:,l,:])    
            for k in range(n): 
                print("G[:,:,k] skew sym ?")
                print(G[:,:,k])

        del F, L_G, tr_L

        self.G = G

    def sparse_G_full(self, n) : 
        # warning no rank condition here 
        G = torch.zeros(n,n,n,device=self.device)
        for k in range(n): 
            F = torch.zeros(n,n,device=self.device)
            F[k,(k+1)%n] = 1
            F = 0.5 * (F - F.T)
            F *= torch.sqrt(torch.tensor(2, dtype=torch.float32))
            G[:,:,k] = F
        
        # check
        validate = False
        if validate:
            L_G = 0.5*torch.einsum('ijk, jmk -> im', G, G)   # ito correction tensor
            tr_L = torch.trace(L_G)
            print("tr_L = " + str(tr_L))
            print("normalisation = " + str(torch.sqrt( - 0.5 * n / tr_L ).item()))
            for l in range(n): 
                print("G[:,l,:] of rank d-1 ?")
                print(G[:,l,:])
            for k in range(n): 
                print("G[:,:,k] skew sym ?")
                print(G[:,:,k])
        del F
        self.G = G

    def sparse_G(self, n) : 
        i_list = []
        j_list = []
        k_list = []
        v_list = []

        for k in range(n):
            i_list.extend([k, (k+1)%n])
            j_list.extend([(k+1)%n, k])
            k_list.extend([k, k])
            coef = 0.5 * torch.sqrt(torch.tensor(2, dtype=torch.float32))
            v_list.extend([coef, -coef])

        indices = torch.tensor([i_list, j_list, k_list], dtype=torch.int64)   # shape (3, 2n); scatter_add_ requires int64
        values  = torch.tensor(v_list, dtype=torch.float32)

        # keep a CPU sparse object for debugging/IO if you want:
        try:
            self.G_sparse_cpu = torch.sparse_coo_tensor(indices, values, size=(n, n, n)).coalesce()
        except Exception:
            # if sparse COO creation on CPU fails for some reason, skip storing CPU sparse
            self.G_sparse_cpu = None

        # move raw arrays to the active device (MPS)
        self.G_I = indices[0].to(self.device)   # (nnz,)
        self.G_J = indices[1].to(self.device)
        self.G_K = indices[2].to(self.device)
        self.G_V = values.to(self.device)       # (nnz,)

        # Optionally delete CPU copies to save RAM
        del indices, values

    def sparse_G_advection(self, n) :
        # All construction (grid, CFL, hyperdiffusion, G/F sparse tensors,
        # Ito correction) lives in transportNoise.build_advection_state;
        # this just wires the result into the SDE's own attributes.
        N = int(round(np.sqrt(n)))
        T_val = self.T.item() if torch.is_tensor(self.T) else self.T
        state = build_advection_state(N, self.anti_aliasing, T_val, self.num_steps_forward,
                                       self.beta_max, self.V0, self.A_beta, self.k_pattern,
                                       self.device)
        self.V0, self.A_beta, self._meanflow_terms = state.V0, state.A_beta, state.meanflow_terms
        self.D_hyper = state.D_hyper
        self.G_I, self.G_J, self.G_K = state.G_I, state.G_J, state.G_K
        self.G_V, self.G_V_I = state.G_V, state.G_V_I
        self.G_sparse_cpu = state.G_sparse_cpu
        self.L_G = state.L_G
        if self.A_beta != 0:
            self.F_I, self.F_J, self.F_K = state.F_I, state.F_J, state.F_K
            self.F_V_R, self.F_V_I = state.F_V_R, state.F_V_I
            self._meanflow_beta_map = state.meanflow_beta_map

    def IJK(self):
        if self.sparseTensor:
            I = self.G_I
            J = self.G_J
            K = self.G_K
            return I, J, K
        else:
            return None, None, None

    def f(self, t, y): # ito drift
        # self.L_G is always the (exact or placeholder, see __init__) Ito
        # correction matrix now, for dense, sparse ring-lattice, and sparse
        # advection (AMSGM) alike, so a single matvec form covers all cases.
        beta_t = self.beta(t)
        beta_t_b = beta_t.reshape(beta_t.shape[0], *([1] * (y.dim() - 1)))  # broadcast over any trailing channel dim
        scaled_y = beta_t_b * y
        if y.dim() > 2:
            fy = torch.einsum('ij, bjc -> bic', self.L_G, scaled_y)
        else:
            fy = torch.einsum('ij, bj -> bi', self.L_G, scaled_y)
        return fy + self.f_strato(t, y)  # add any extra Stratonovich drift (e.g. hyperdiffusion)

    def f_strato(self, t, y):  # stratonovich drift, i.e. the RATE f (dt applied later by the scheme, see sde_scheme)
        result = torch.zeros_like(y)
        # Hyperdiffusion, stepped explicitly like any other drift term
        # (already capped for RK4 stability, see build_hyperdiffusion_capped).
        if self.AMSGM and self.D_hyper is not None:
            beta_t = self.beta(t)
            beta_t_b = beta_t.reshape(beta_t.shape[0], *([1] * (y.dim() - 1)))  # broadcast over any trailing channel dim
            scaled_y = beta_t_b * y
            rate = self.D_hyper.reshape(1, -1, *([1] * (scaled_y.dim() - 2)))
            result = result - rate * y
        if self.AMSGM and self.A_beta != 0:
            result = result + self._meanflow_drift(t, y)
        return result

    def _meanflow_drift(self, t, y):
        """Deterministic mean-flow advection F Q(t) = sum_k beta_t^R(k)
        F^{k,R} Q + beta_t^I(k) F^{k,I} Q, one term per (k1,k2) in
        self._meanflow_terms (default: a Taylor-Green moving-vortex
        streamfunction, see transportNoise.grid_k.taylor_green_terms).
        Reuses EMstep to combine with beta(t), like g()'s noise output is
        combined with a random dW."""
        beta_R, beta_I = meanflow_beta_vectors(t, self._meanflow_beta_map, y.shape[1], y.device, y.dtype)
        sigma_R, sigma_I = sparse_yJ_products(y, self.F_J, self.F_V_R, self.F_V_I)
        return EMstep(torch.zeros_like(y), 1.0, (sigma_R, sigma_I), (beta_R, beta_I),
                      sparse=True, I=self.F_I, K=self.F_K)

    def div_Sigma(self, t, y):
        return 2*self.f(t,y)

    def g(self, t, y, sparse = False):
        """G^R (skew, per-channel) diffusion coefficient, driven by
        dB^R_t(k). For AMSGM, also returns G^I (symmetric, cross-channel),
        driven by the independent dB^I_t(k) -- see
        transportNoise.grid_k.build_sparse_G. Returns a single tensor
        normally, or (g_R, g_I) when AMSGM."""
        beta_t = self.beta(t)
        # broadcast beta_t (B,1) against y, which may carry a trailing
        # real/imag channel dim (B,n,2) when FFTfields, not just (B,n)
        beta_t = beta_t.reshape(beta_t.shape[0], *([1] * (y.dim() - 1)))
        if sparse:
            # extract sparse G indices
            I, J, K = self.IJK()
            scaled_y = (beta_t**0.5) * y
            if self.AMSGM:
                g_R, g_I = sparse_yJ_products(scaled_y, J, self.G_V, self.G_V_I)
                return g_R, g_I
            V = self.G_V.reshape(1, -1, *([1] * (y.dim() - 2)))
            g_R = V * mps_safe_gather(scaled_y, 1, J)
            return g_R
        else:
            return torch.einsum('ijk, bj -> bik', self.G, (beta_t**0.5) * y  )         # diffusion part
    
    def sample(self, t, y0, return_noise=False):
        return self.sample_scheme(t, y0, return_noise=return_noise,
                                   keep_all_samples=False).to(self.device)

    def gen_radial_distribution(self,num_samples): 
        U = torch.rand(num_samples,device=self.device)   # uniform         
        # could be replaced by KS density
        if self.norm_sampler == "ecdf":
            r_gen = torch.quantile(self.r_T, U).reshape(num_samples,1)
        else:
            r_gen = torch.from_numpy(self.kde.sample(num_samples)).to(torch.float32).to(device)
            if not (self.norm_map == "log"):
                mask_r_gen = (r_gen < 0).float()
                r_gen =  (1. - mask_r_gen) * r_gen
                del mask_r_gen

        if self.norm_map == "log":
            r_gen = torch.exp(r_gen) - 1e-6

        validate = False
        if validate:
            r_plot = r_gen.clone().detach()
            plt.hist(r_plot, bins = 100, alpha = 0.5, density = True)
            time.sleep(0.5)
            plt.show(block=False)
            plt.savefig("radial_distribution.png")
            plt.pause(1)
            plt.close()
        
        del U

        return r_gen

    def _radius_and_direction_to_native(self, r, s):
        """
        r*s is a real vector of the pointwise pixel count (self.dim), drawn
        as a radius times a uniform direction on the sphere -- the natural
        parametrization for MSGMsde's energy-conserving latent distribution
        (see latent_sample). For FFTfields, the SDE's own state is the
        Fourier-domain representation, so r*s (a real, physical-space-shaped
        vector) is treated as that physical-space image and FFT'd: by
        Parseval's exact identity ||fft2(v)|| = N*||v|| for ANY real image v
        (not just on average -- same identity grid.a0() relies on), scaling
        by r/N before the FFT gives exactly ||result|| = r with no need to
        compute the FFT's actual norm and rescale.
        """
        if self.FFTfields:
            N = int(round(self.dim ** 0.5))
            return spatial_flat_to_fourier((r / N) * s)
        return r * s

    def latent_sample(self,num_samples, n):
        # init from prior
        r = self.gen_radial_distribution(num_samples)
        s = randu_on_sphere((num_samples, self.dim),device = self.device)
        return self._radius_and_direction_to_native(r, s)

    def cond_latent_sample(self,t_, T, x):
        # conditionnal latent sample of yT knowing x=y0
        x_det = x.clone().detach().to(self.device)
        r_x = torch.linalg.norm(x_det.reshape(x_det.shape[0], -1), dim= 1).reshape(x.shape[0],1)
        s = randu_on_sphere((x.shape[0], self.dim),device = self.device)
        return self._radius_and_direction_to_native(r_x, s)
    
    def log_latent_pdf(self,yT):
        # WARNING : the nomalizing constant is not correct here
        # WARNING : miss || x ||^{d-1} / S_{d-1}
        yT_det = yT.clone().detach()
        r_yT = torch.linalg.norm(yT_det.reshape(yT_det.shape[0], -1), dim= 1)
        del yT
        r_yT = r_yT.reshape(len(r_yT),1)
        return torch.tensor(self.kde.score_samples(r_yT.cpu())).to(torch.float32).to(self.device) - self.cst_log_dens

###################################################################################################

### Reverse SDE
def sample_rademacher(shape, device):
    return (torch.rand(*shape,device=device).ge(0.5)).float() * 2 - 1

def sample_gaussian(shape, device):
    return torch.randn(*shape, device=device)

def randu_on_sphere(shape, device): 
    # Let X_i be N(0,1) and  lambda^2 =2 sum X_i^2, then (X_1,...,X_d) / lambda  is uniform in S^{d-1}
    X = torch.randn(*shape,device=device)
    X_norm = torch.linalg.norm(X, dim = 1).reshape(shape[0],1)
    X =  X / X_norm 
    # del X_norm
    return X

def sample_v(shape, device, vtype='rademacher'):
    if vtype == 'rademacher':
        return sample_rademacher(shape, device=device)
    elif vtype == 'normal' or vtype == 'gaussian':
        return sample_gaussian(shape, device=device)
    elif vtype == 'uniform' :
        return randu_on_sphere(shape, device=device)
    else:
        Exception(f'vtype {vtype} not supported')

class PluginReverseSDE(torch.nn.Module):
    """
    inverting a given base sde with drift `f` and diffusion `g`, and an inference sde's drift `a` by
    f <- g a - f
    g <- g
    (time is inverted)
    """
    def __init__(self, base_sde, drift_a, T, vtype='rademacher', debias=False, ssm_intT=False, deviceReverseSDE='cpu', n_slices=1):
        super().__init__()
        self.base_sde = base_sde.to(deviceReverseSDE)
        self.a = drift_a
        self.T = T.to(deviceReverseSDE)
        self.vtype = vtype
        self.ssm_intT = ssm_intT
        self.debias = debias
        self.deviceReverseSDE = deviceReverseSDE
        # number of independent Hutchinson projections averaged per SSM loss
        # evaluation: reduces the trace estimator's variance ~1/n_slices at
        # the cost of n_slices extra vector-Jacobian products. Since the
        # SPDE's own time integration (num_steps_forward RK4 steps) dominates
        # cost, a larger n_slices (e.g. sqrt(d) = npixel) is cheap relatively.
        self.n_slices = n_slices

    # Drift
    def mu(self, t, y, lmbd=0.):
        return self.ga_m_drift(self.T-t, y, lmbd)

    # Drift of reserve generative SDE
    def ga_m_drift(self, s, y, lmbd=0.):
        return (1. - 0.5 * lmbd) * self.ga(s, y) - self.base_sde.f(s, y) + (1. - lmbd) * self.base_sde.div_Sigma(s, y)

    def _eval_a(self, y, s):
        """
        Evaluate the score network a(). a(x_t) plays the same structural
        role as the SDE's noise dBt: real, one scalar per mode, regardless
        of whether y itself is real (dense/non-FFT case) or the complex
        Fourier state (FFTfields, y: (B,n,2)). For FFTfields, a()'s own
        FFTfield=True handles the ifft2 conversion of y to the spatial image
        the network natively operates on, but always returns a real (B,n)
        result (never re-FFT'd -- see VorticityUNet.forward's docstring),
        matching how ga() must combine a with g: by scaling g's own (re,im)
        channels with the real aK, never by treating a itself as complex.
        """
        if y.dim() == 3 and y.shape[-1] == 2:
            return self.a(y, s, FFTfield=True)
        return self.a(y, s)

    def ga(self, s, y, return_a=False):
        """
        Computes g(y)*a(y). y may be Fourier-domain flat (B,n,2) -- the
        representation ga_m_drift/mu (the reverse-SDE sampling path) use --
        or spatial-domain flat (B,n) -- what ssm_loss passes for FFTfields
        (see ssm()); the result is returned in that same representation,
        and a is also returned when return_a=True (ssm_loss needs it for
        mNu).

        a(x_t) plays the same structural role as the noise dBt in the
        forward SDE (dx_t = G(x_t) o dBt): a() itself always stays real,
        one scalar per pixel, spatial (see _eval_a/VorticityUNet.forward).
        For AMSGM, the true noise is 2-dimensional per mode (dB^R_t(k),
        dB^I_t(k) -- see transportNoise.grid_k.build_sparse_G), so a's own
        FFT (Hermitian-symmetric, like any real field's) supplies the
        matching 2 channels: a_fft[...,0] pairs with G^R, a_fft[...,1]
        pairs with G^I -- never by converting a itself to Fourier/complex
        the way y is (that would introduce spurious re*im cross terms).
        This mirrors exactly how EMstep (sde_scheme.py) broadcasts the two
        real dW_R/dW_I across sigma_R/sigma_I.
        """
        is_fourier = (y.dim() == 3 and y.shape[-1] == 2)
        y_fft = y if is_fourier else spatial_flat_to_fourier(y)
        g = self.base_sde.g(s, y_fft, self.base_sde.sparseTensor)
        a = self._eval_a(y, s.squeeze())                # (B,n) always real, spatial
        if self.base_sde.sparseTensor:
            I, J, K = self.base_sde.IJK()
            if self.base_sde.AMSGM:
                g_R, g_I = g
                a_fft = spatial_flat_to_fourier(a)          # (B,n,2): channels match dB^R/dB^I per mode
                aK_R = mps_safe_gather(a_fft[..., 0], 1, K)
                aK_I = mps_safe_gather(a_fft[..., 1], 1, K)
                prod = g_R * aK_R.unsqueeze(-1) + g_I * aK_I.unsqueeze(-1)  # (B,nnz,2)
            else:
                aK = mps_safe_gather(a, 1, K)                   # (B,nnz) real
                if g.dim() > aK.dim():
                    aK = aK.unsqueeze(-1)      # broadcast the real scalar across g's (re,im) channels
                prod = g * aK                # (B,nnz) or (B,nnz,2)
            dx_fft = torch.zeros(y_fft.shape[0], y_fft.shape[1], *y_fft.shape[2:], device=y_fft.device, dtype=prod.dtype)
            index = I.unsqueeze(0).expand(y_fft.shape[0], -1)
            if prod.dim() > 2:
                index = index.unsqueeze(-1).expand(-1, -1, prod.shape[-1])
            mps_safe_scatter_add_(dx_fft, 1, index, prod)
        else:
            # g is either a dense (B,n,n) diffusion matrix (needs a matvec via
            # einsum), or an elementwise/diagonal diffusion coefficient the
            # same shape as `a` (just multiply).
            if g.shape == a.shape:
                dx_fft = g * a
            else:
                dx_fft = torch.einsum('bij, bj -> bi', g, a)
        dx = dx_fft if is_fourier else fourier_flat_to_spatial(dx_fft)
        return (dx, a) if return_a else dx


    # Stratonovich Drift
    def mu_Strato(self, t, y, lmbd=0.):
        return self.mu(t, y, lmbd) - 0.5 * (1. - lmbd) * self.base_sde.div_Sigma(self.T-t, y)

    # Diffusion
    def sigma(self, t, y, lmbd=0., sparse=False):
        g = self.base_sde.g(self.T-t, y, sparse)
        scale = (1. - lmbd) ** 0.5
        if isinstance(g, tuple):
            return tuple(scale * gi for gi in g)
        return scale * g

    # # WARNING : DSM is not relevant in MSGM
    # # SSM needs to be defined instead
    # @torch.enable_grad()
    # def dsm(self, x):
    #     """
    #     denoising score matching loss
    #     """
    #     if self.debias:
    #         t_ = self.base_sde.sample_debiasing_t([x.size(0), ] + [1 for _ in range(x.ndim - 1)])
    #     else:
    #         t_ = torch.rand([x.size(0), ] + [1 for _ in range(x.ndim - 1)]).to(x) * self.T
    #     y, target, std, g = self.base_sde.sample(t_, x, return_noise=True)
    #     a = self.a(y, t_.squeeze())

    #     return ((a * std / g + target) ** 2).view(x.size(0), -1).sum(1, keepdim=False) / 2
    #     # / g is not convenient for g being a dense matrix of rank d-1...

    @torch.enable_grad()
    def ssm(self, x):
        """
        estimating the SSM loss of the plug-in reverse SDE
        """
        t_,x,y = self.sample_txy(x)
        if self.base_sde.FFTfields and y.dim() == 3 and y.shape[-1] == 2:
            y = fourier_flat_to_spatial(y)   # differentiate w.r.t. the spatial state, see ga()
        y.requires_grad_()
        return self.ssm_loss(t_,x,y)

    def _hutchinson_trace(self, mu_to_div, y, batch_size):
        """
        Averages self.n_slices independent Hutchinson projections of
        mu_to_div's divergence w.r.t. y, reducing the (unbiased) trace
        estimator's variance by ~1/n_slices. All calls share the same
        mu_to_div/y computation graph (retain_graph=True throughout, since
        it must survive n_slices vector-Jacobian products, not just one).
        """
        mMu_slices = []
        for i in range(self.n_slices):
            with torch.no_grad():
                v = sample_v(y.shape, vtype=self.vtype, device=self.deviceReverseSDE).to(y)
            retain = self.training or (i < self.n_slices - 1)
            grad_i = torch.autograd.grad(mu_to_div, y, v, create_graph=self.training, retain_graph=retain)[0]
            mMu_slices.append((grad_i * v).reshape(batch_size, -1).sum(1, keepdim=False))
        return torch.stack(mMu_slices, dim=0).mean(0)

    def _mu_to_div_and_a(self, t_, y):
        """
        Computes (mu_to_div, a) for the SSM loss.
        mu_to_div = ga(t,y) - f(t,y) + 0.5*div_Sigma(t,y) always (this is
        ga_m_drift(t,y,0.) - 0.5*div_Sigma(t,y) simplified -- see ga_m_drift).
        y may be spatial (B,n, FFTfields) or Fourier (B,n,2, otherwise);
        ga() handles both directly. f/div_Sigma are Fourier-domain-only
        operators, so for spatial y they're evaluated on its Fourier
        conversion and brought back to spatial to match.
        """
        ga_val, a = self.ga(t_, y, return_a=True)
        if y.dim() == 2:
            y_fft = spatial_flat_to_fourier(y)
            f = fourier_flat_to_spatial(self.base_sde.f(t_, y_fft))
            div_sigma = fourier_flat_to_spatial(self.base_sde.div_Sigma(t_, y_fft))
        else:
            f = self.base_sde.f(t_, y)
            div_sigma = self.base_sde.div_Sigma(t_, y)
        mu_to_div = ga_val - f + 0.5 * div_sigma
        return mu_to_div, a

    @torch.enable_grad()
    def ssm_loss(self, t_, x, y):
        """
        estimating the SSM loss of the plug-in reverse SDE by estimating div(mu) using the Hutchinson trace estimator
        """
        mu_to_div, a = self._mu_to_div_and_a(t_, y)
        mMu = self._hutchinson_trace(mu_to_div, y, x.size(0))
        if self.base_sde.AMSGM:
            # noise is 2-dim per mode (dB^R_t(k), dB^I_t(k)); a's own FFT
            # supplies the matching 2 channels (see ga()'s docstring)
            a_nu = spatial_flat_to_fourier(a)
        else:
            a_nu = a
        mNu = (a_nu ** 2).reshape(x.size(0), -1).sum(1, keepdim=False) / 2
        return mMu + mNu

    def sample_txy(self, x):
        """
        sampling t,x,y
        """
        with torch.no_grad():
            if self.ssm_intT:
                # GRIDDED t uniformly between [0, T], truncated at t_epsilon
                batchsize = x.shape[0]
                dim = x.shape[1]
                t_, mask_le_t_eps = self.sample_t_linspace(x)
                y = self.base_sde.sample_scheme_allt(x, 
                                                     keep_all_samples=True,
                                                     include_t0=False)
                y = y[~mask_le_t_eps,:,:]

                # n_subsample = 4
                # t_ = t_[0:-1:n_subsample]  # subsample in time
                # y = y[0:-1:n_subsample,:,:]

                if any(mask_le_t_eps):
                    print(str((100*mask_le_t_eps.sum().item()/mask_le_t_eps.shape[0])) + '%' + ' of time steps are truncated at t_epsilon')

                num_steps = t_.shape[0]
                t_ = t_[:,None].repeat(1, batchsize)
                x = x[None,:,:].repeat(num_steps,1,1)

                t_ = t_.reshape((batchsize*num_steps,1))
                x = x.reshape((batchsize*num_steps,dim))
                y = y.reshape((batchsize*num_steps,dim))
                # WARNING order='F' IS NOT USED 
            else:
                # sampling t uniformly between [0, T], truncated at t_epsilon
                t_ = self.sample_t(x)
                y = self.base_sde.sample(t_, x)
        return t_,x,y

    def sample_t(self, x):
        """
        sampling t uniformly between [0, T], truncated at t_epsilon
        """
        t_ = torch.rand([x.size(0), ] + [1 for _ in range(x.ndim - 1)]).to(x) * self.T

        # truncated at t_epsilon for t < t_epsilon
        mask_le_t_eps = (t_ <= self.base_sde.t_epsilon).float()
        t_ = mask_le_t_eps * self.base_sde.t_epsilon + (1. - mask_le_t_eps) * t_
        return t_
    
    def sample_t_linspace(self, x):
        """
        GRIDDED t uniformly between [0, T]
        """
        dt = self.T / self.base_sde.num_steps_forward
        t_ = torch.linspace(dt[0], self.T[0], self.base_sde.num_steps_forward ).to(device)

        # truncated at t_epsilon for t < t_epsilon
        mask_le_t_eps = (t_ <= self.base_sde.t_epsilon)
        t_ = t_[~mask_le_t_eps]
        
        return t_,mask_le_t_eps
    
    def elbo_random_t_slice(self, x):
        """
        estimating the ELBO of the plug-in reverse SDE by sampling t uniformly between [0, T], and by estimating
        div(mu) using the Hutchinson trace estimator
        """

        qt = 1 / self.T
        loss_ssm = self.ssm(x)/ qt

        t_,x,y = self.sample_txy(x)
        yT = self.cond_latent_sample(t_, self.base_sde.T, x)
        lp = self.base_sde.log_latent_pdf(yT).reshape(x.size(0), -1).sum(1)

        return lp - loss_ssm
    
    def latent_sample(self,num_samples, n):
        # init from prior
        return self.base_sde.latent_sample(num_samples, n) 
    
    def cond_latent_sample(self,t_, T, x):
        # conditionnal latent sample of yT knowing x=y0
        return self.base_sde.cond_latent_sample(t_, T, x)
